require('./scripts/input-method-indicator')
require('./scripts/auto-switch-input-method')
require('./scripts/defeating-paste-blocking')
require('./scripts/show-launchpad')
require('./scripts/wifi-mute')
require('./scripts/caffeinated')
require('./scripts/ring')
require('./scripts/magspeed-smooth-scrolling-fix')
