require('./modules/arrow_keys_remapping')
require('./modules/auto_switch_input_method')
-- require('./modules/caffeine')
require('./modules/defeating_paste_blocking')
require('./modules/input_method_indicator')
-- require('./modules/launchpad_shortcut_fix')
require('./modules/magspeed_smooth_scrolling_fix')
require('./modules/ring')
-- require('./modules/wifi_mute')
